name: ipv6

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  sync-m3u:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Create TV directory
        run: mkdir -p tv

      - name: Download and process M3U
        run: |
          wget -q --tries=3 --timeout=20 "https://live.fanmingming.cn/tv/m3u/ipv6.m3u" -O tv/input.m3u || exit 1
          sed -i -E 's/(group-title=")([^"]{2})[^"]*(")/\1\2\3/g' tv/input.m3u
          sed -i -E 's/(,CCTV)([0-9]+)(,*)/,CCTV-\2\3/g' tv/input.m3u
          awk '/^#EXTINF/{if(!a[$0]++)print;next}1' tv/input.m3u > tv/output.m3u
          echo -e "#EXTM3U x-tvg-url=\"https://live.fanmingming.cn/e.xml\"\n# $(date +'%Y-%m-%d %H:%M:%S')" > tv/header.txt
          cat tv/header.txt tv/output.m3u > tv/ipv6.m3u
          rm tv/input.m3u tv/output.m3u tv/header.txt
          
      - name: 提交更改
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add tv/ipv6.m3u
          git diff-index --quiet HEAD || git commit -m "Auto update M3U: $(date +'%Y-%m-%d')"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: false
